version: "3"

services:
  db:
    image: postgres:15
    container_name: fsit-db
    environment:
      - POSTGRES_DB=fsitdb
      - POSTGRES_USER=fsit
      - POSTGRES_PASSWORD=xrbp1qu7gs3s6r54
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  nginx:
    image: "nginx"
    container_name: fsit-nginx
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./mediafiles:/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: fsit-web
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations home --noinput && 
                      python manage.py migrate --noinput && 
                      python manage.py initadmin && 
                      python manage.py collectstatic --no-input && 
                      gunicorn fsit.wsgi:application --bind 0.0.0.0:8000 --timeout 120 -k gevent --workers 4"
    ports:
      - "8000:8000"
    depends_on:
      - db