name: CI/CD for fsitsevice.com

on:
  push:
    branches:
      - main
      - dev

env:
  IMAGE_NAME: mezbauddin.com
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SERVER_HOST: ${{ secrets.VPS_IP_ADRESS }}
  SERVER_USERNAME: ${{ secrets.SSH_USERNAME }}
  SERVER_PASSWORD: ${{ secrets.SSH_PASSWORD }}
#   TFE_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
#   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#   TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}


jobs:
  build-push-deploy-provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image and Push
        run: |
            docker compose -f docker-compose.dev.yml build
            docker compose -f docker-compose.dev.yml push

      - name: Login to Server/VPS/VM/Drolet
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.VPS_IP_ADRESS }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}

      - name: Deploy to Digital ocean droplet.
        run: |
        
          # echo "$DOCKER_PASSWORD" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \

          if [[ "refs/heads/dev" == "refs/heads/dev" ]]; then
            COMPOSE_FILE=docker-compose.dev.yml
          else
            COMPOSE_FILE=docker-compose.yml
          fi        
          echo "Using Docker Compose file: $COMPOSE_FILE" && \
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f $COMPOSE_FILE down || true && \
          docker-compose -f $COMPOSE_FILE pull && \
          docker-compose -f $COMPOSE_FILE up -d